micronaut:
  application:
    name: rest
grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    pix:
      address: '0.0.0.0:50051'
      plaintext: true
      max-retry-attempts: 5
